# Generated by Django 4.0.2 on 2022-08-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_rename_realise_date_phone_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(),
        ),
    ]
